# Generated by Django 6.0.6 on 2026-07-01 18:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
                ('raw_markdown', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_product', to='search.rawmarkdown')),
                ('search_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_product', to='search.searchresult')),
            ],
            options={
                'verbose_name_plural': 'Parsed products',
            },
        ),
    ]
