# Generated by Django 6.0.6 on 2026-07-14 16:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_parsedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('searching', 'Searching'), ('crawling', 'Crawling'), ('parsing', 'Parsing'), ('normalizing', 'Normalizing'), ('comparing', 'Comparing'), ('recommending', 'Recommending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('compared_at', models.DateTimeField(auto_now_add=True)),
                ('search_query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comparison', to='search.searchquery')),
            ],
            options={
                'verbose_name_plural': 'Comparison results',
            },
        ),
        migrations.CreateModel(
            name='NormalizedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('normalized_specs', models.JSONField(default=dict)),
                ('normalized_price', models.JSONField(default=dict)),
                ('normalized_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized', to='search.parsedproduct')),
            ],
            options={
                'verbose_name_plural': 'Normalized products',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('search_query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='search.searchquery')),
            ],
            options={
                'verbose_name_plural': 'Recommendations',
            },
        ),
    ]
